# Generated by Django 5.2 on 2025-05-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('reprogramdo', 'Reprogramado'), ('agotado', 'Agotado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
