# Generated by Django 5.1 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_refundrequest_approved_refundrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
