# Generated by Django 5.1 on 2025-04-27 23:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(default=app.models.code_generator, max_length=50, unique=True),
        ),
    ]
