# Generated by Django 5.2 on 2025-05-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_state'),
        ('app', '0004_ticket_price'),
    ]

    operations = [
    ]
