# Generated by Django 5.2 on 2025-05-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favorite'),
        ('app', '0005_merge_0002_event_state_0004_ticket_price'),
    ]

    operations = [
    ]
