# Generated by Django 5.1 on 2025-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ticket_ticket_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
