# Generated by Django 5.2 on 2025-05-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250528_1607'),
        ('app', '0006_merge_20250528_1832'),
        ('app', '0006_merge_20250528_1907'),
    ]

    operations = [
    ]
