# Generated by Django 5.1 on 2025-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ticket_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('VIP', 'VIP')], default='General', max_length=10),
        ),
    ]
