# Generated by Django 5.2 on 2025-04-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_comment_refundrequest"),
        ("app", "0007_venue_comment_ticket_event_venue"),
    ]

    operations = []
