# Generated by Django 5.1 on 2025-04-29 18:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ticket_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_general',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
    ]
