name: ci
# Este workflow se ejecuta cuando ocurre alguno de los siguientes eventos:
# - Se publica una nueva release
# - Se hace push a la rama main
# - Se crea o actualiza un pull request hacia la rama main
on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    # El job se ejecuta en un runner con Ubuntu
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  # Este job depende de que el job "build" haya finalizado correctamente
  # Ejecuta los test unitarios y de integración
  unit-integration-tests:
    runs-on: ubuntu-latest
    name: Tests Unitarios e Integración
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar tests Django (unitarios e integración)
        run: |
          python manage.py test app/test/test_unit app/test/test_integration
  # Este job depende de que el job "build" haya finalizado correctamente
  # Ejecuta los test e2e
  e2e:
    runs-on: ubuntu-latest
    name: Tests End-to-End
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest playwright
          playwright install

      - name: Ejecutar tests E2E
        run: |
          python manage.py test app/test/test_e2e
